#!/usr/bin/env python
print "Content-Type: text/html; charset=ISO-8859-1"
print ""


import ccdb_web_config as config
config.python_config()


from wheezy.template.engine import Engine
from wheezy.template.ext.core import CoreExtension
from wheezy.template.loader import FileLoader

search_path = ['templates/']
engine = Engine(loader=FileLoader(search_path), extensions=[CoreExtension()])
template = engine.get_template('doc.html')
print(template.render({
    "site_url":config.site_url,
    "site_cgi_root": config.site_cgi_root,
    "site_root":config.site_root

}))

