#!/usr/bin/env python

print "Content-Type: text/html; charset=ISO-8859-1"
print ""


from wheezy.template.engine import Engine
from wheezy.template.ext.core import CoreExtension
from wheezy.template.loader import FileLoader

import ccdb_web_config as config
config.python_config()

import ccdb
prov = ccdb.AlchemyProvider()
prov.connect("mysql://ccdb_user@127.0.0.1/ccdb")
d = prov.get_root_directory()

import  os

def make_html_dir_info(dir):
    """

    """



def dir_to_ul(dir, level = 0):
    """

    :param dir: Directory
    :type dir: ccdb.Directory
    :return: String
    :rtype; str
    """

    if not len(dir.sub_dirs) and not len(dir.type_tables): return ""

    spaces = level * "      "
    result = spaces + '<!-- ' + dir.name + '--> ' +  os.linesep +\
             spaces + '<ul>' +  os.linesep

    #print subdirectories
    for sub_dir in dir.sub_dirs:
        result = result + \
                 spaces + '  <li>' + os.linesep +\
                 spaces + '    <span class="directory">' + sub_dir.name + '</span>' +  os.linesep
        if len(dir.sub_dirs):
            result = result + dir_to_ul(sub_dir, level+1) +  os.linesep
        result = result + spaces + '  </li>' +  os.linesep

    #print type tables
    for table in dir.type_tables:
        assert(isinstance(table, ccdb.TypeTable))
        result = result +\
                 spaces + '  <li>' + os.linesep +\
                 spaces + '    <span class="directory">' + table.name + '</span>' +  os.linesep +\
                 spaces + '  </li>' + os.linesep

    #close
    result = result + spaces + "</ul>" +  os.linesep
    return result

tree_html = "<!-- TREE -->" +  os.linesep + dir_to_ul(d,1) +  os.linesep

search_path = ['templates/']
engine = Engine(
    loader=FileLoader(search_path),
    extensions=[CoreExtension()]
)
template = engine.get_template('template.html')
sd = d.sub_dirs[0]
print(template.render({"directory": sd, "dir_html":tree_html}))


#print "<p>done!</p>" + .name

