#!/usr/bin/env python
print "Content-Type: text/html; charset=ISO-8859-1"
print ""


import ccdb_web_config as config
config.python_config()

import cgi

#------------ RENDER --------------------------------
from wheezy.template.engine import Engine
from wheezy.template.ext.core import CoreExtension
from wheezy.template.loader import FileLoader
template_engine = Engine(loader=FileLoader(['templates/']), extensions=[CoreExtension()])
template = template_engine.get_template('versions.html')



#------ CCDB DATABASE API-----------------------------
import ccdb
prov = ccdb.AlchemyProvider()
prov.connect(config.connection_string)



form = cgi.FieldStorage()
table = form.getfirst("table", None)
if table:
    assignments = prov.get_assignments(table) #"/test/test_vars/test_table")


else:
    assignments = None


print(template.render({
    "site_url":config.site_url,
    "site_cgi_root": config.site_cgi_root,
    "site_root":config.site_root,
    "assignments":assignments,
    "table":table
}))

