language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r python/requirements.txt
# command to run tests
before_install:
  - source environment.bash
script:
  - python python/tests/integ_test_provider_sqlite.py
