#!/usr/bin/python
###MEW Changed to use the local Python. M. Wise, 3/16/2015. 
###MEW #!/apps/python/python-2.7.1/bin/python
print "Content-Type: text/html; charset=ISO-8859-1"
print ""


import ccdb_web_config as config
config.python_config()

import cgi

#------------ RENDER --------------------------------
from wheezy.template.engine import Engine
from wheezy.template.ext.core import CoreExtension
from wheezy.template.loader import FileLoader
template_engine = Engine(loader=FileLoader(['templates/']), extensions=[CoreExtension()])
template = template_engine.get_template('show_request.html')



#------ CCDB DATABASE API-----------------------------
import ccdb
from ccdb.path_utils import ParseRequestResult, parse_request
from ccdb.model import User

prov = ccdb.AlchemyProvider()
prov.connect(config.connection_string)


assignment = None #this is the desired assignment
variation = ""
created   = ""
author    = ""
run_range = ""
comment   = ""


#get request from web form
str_request = cgi.FieldStorage().getfirst("request", None)
#str_request = "/test/test_vars/test_table:0:default:2012-10-30_23-48-41"

if str_request:

    #parse request and prepare time
    request = parse_request(str_request)
    assert isinstance(request, ParseRequestResult)
    time = request.time if request.time_is_parsed else None

    #query database for assignments for this request
    assignments = prov.get_assignments(request.path, request.run, request.variation, time)

    #get first assignment
    if assignments and len(assignments)!=0 :
        assignment = assignments[0]
        assert (isinstance(assignment, ccdb.Assignment))

        variation = assignment.variation.name
        created = str(assignment.created)
        run_range = str(assignment.run_range.min)+" - "
        run_range = run_range + (str(assignment.run_range.max) if assignment.run_range.max!=2147483647 else "inf.")
        comment = assignment.comment.replace("\n", "<br />")
        try:
            author = prov.session.query(User).filter(User.id == assignment.author_id).one().name
        except Exception as ex:
            print ex


#RENDER
print(template.render({
    "site_url":config.site_url,
    "site_cgi_root": config.site_cgi_root,
    "site_root":config.site_root,
    "assignment":assignment,
    "request":str_request,
    "variation":    variation,
    "created": created,
    "author": author,
    "run_range": run_range,
    "comment":comment
}))

