/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ccdb {

using System;
using System.Runtime.InteropServices;

public class DMySQLDataProvider : DDataProvider {
  private HandleRef swigCPtr;

  internal DMySQLDataProvider(IntPtr cPtr, bool cMemoryOwn) : base(ccdb_csllapiPINVOKE.DMySQLDataProvider_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DMySQLDataProvider obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DMySQLDataProvider() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccdb_csllapiPINVOKE.delete_DMySQLDataProvider(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DMySQLDataProvider() : this(ccdb_csllapiPINVOKE.new_DMySQLDataProvider(), true) {
  }

  public override bool Connect(string connectionString) {
    bool ret = ccdb_csllapiPINVOKE.DMySQLDataProvider_Connect(swigCPtr, connectionString);
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool IsConnected() {
    bool ret = ccdb_csllapiPINVOKE.DMySQLDataProvider_IsConnected(swigCPtr);
    return ret;
  }

  public override void Disconnect() {
    ccdb_csllapiPINVOKE.DMySQLDataProvider_Disconnect(swigCPtr);
  }

  public override DDirectory GetDirectory(string path) {
    IntPtr cPtr = ccdb_csllapiPINVOKE.DMySQLDataProvider_GetDirectory(swigCPtr, path);
    DDirectory ret = (cPtr == IntPtr.Zero) ? null : new DDirectory(cPtr, false);
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
