/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ccdb {

using System;
using System.Runtime.InteropServices;

public class DRunRange : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DRunRange(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DRunRange obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DRunRange() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ccdb_csllapiPINVOKE.delete_DRunRange(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DRunRange() : this(ccdb_csllapiPINVOKE.new_DRunRange(), true) {
  }

  public int GetId() {
    int ret = ccdb_csllapiPINVOKE.DRunRange_GetId(swigCPtr);
    return ret;
  }

  public int GetMax() {
    int ret = ccdb_csllapiPINVOKE.DRunRange_GetMax(swigCPtr);
    return ret;
  }

  public int GetMin() {
    int ret = ccdb_csllapiPINVOKE.DRunRange_GetMin(swigCPtr);
    return ret;
  }

  public string GetName() {
    string ret = ccdb_csllapiPINVOKE.DRunRange_GetName(swigCPtr);
    return ret;
  }

  public string GetComment() {
    string ret = ccdb_csllapiPINVOKE.DRunRange_GetComment(swigCPtr);
    return ret;
  }

  public void SetId(int val) {
    ccdb_csllapiPINVOKE.DRunRange_SetId(swigCPtr, val);
  }

  public void SetMax(int val) {
    ccdb_csllapiPINVOKE.DRunRange_SetMax(swigCPtr, val);
  }

  public void SetMin(int val) {
    ccdb_csllapiPINVOKE.DRunRange_SetMin(swigCPtr, val);
  }

  public void SetName(string val) {
    ccdb_csllapiPINVOKE.DRunRange_SetName(swigCPtr, val);
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetComment(string val) {
    ccdb_csllapiPINVOKE.DRunRange_SetComment(swigCPtr, val);
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int min, int max) {
    ccdb_csllapiPINVOKE.DRunRange_SetRange(swigCPtr, min, max);
  }

  public SWIGTYPE_p_time_t GetCreatedTime() {
    SWIGTYPE_p_time_t ret = new SWIGTYPE_p_time_t(ccdb_csllapiPINVOKE.DRunRange_GetCreatedTime(swigCPtr), true);
    return ret;
  }

  public void SetCreatedTime(SWIGTYPE_p_time_t val) {
    ccdb_csllapiPINVOKE.DRunRange_SetCreatedTime(swigCPtr, SWIGTYPE_p_time_t.getCPtr(val));
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_time_t GetModifiedTime() {
    SWIGTYPE_p_time_t ret = new SWIGTYPE_p_time_t(ccdb_csllapiPINVOKE.DRunRange_GetModifiedTime(swigCPtr), true);
    return ret;
  }

  public void SetModifiedTime(SWIGTYPE_p_time_t val) {
    ccdb_csllapiPINVOKE.DRunRange_SetModifiedTime(swigCPtr, SWIGTYPE_p_time_t.getCPtr(val));
    if (ccdb_csllapiPINVOKE.SWIGPendingException.Pending) throw ccdb_csllapiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
