import distutils.sysconfig
import os;
import re
import sys

#==== SWIGSharedLibrary ================================
def SWIGSharedLibrary(env, library, sources, **args):
	swigre = re.compile('(.*).i')
	if env.WhereIs('swig') is None:
		sourcesbis = []
		for source in sources:
			cName = swigre.sub(r'\1_wrap.c', source)
			cppName = swigre.sub(r'\1_wrap.cxx', source)
			if os.path.exists(cName):
				sourcesbis.append(cName)
			elif os.path.exists(cppName):
				sourcesbis.append(cppName)
			else:
				sourcesbis.append(source)
	else:
		sourcesbis = sources
	if 'SWIGFLAGS' in args:
		args['SWIGFLAGS'] += ['-python']
	else:
		args['SWIGFLAGS'] = ['-python'] + env['SWIGFLAGS']
	args['SHLIBPREFIX']=""
	if sys.version >= '2.5':
		args['SHLIBSUFFIX']=".pyd"
 
	cat=env.SharedLibrary(library, sourcesbis, **args)
	return cat
#==== end of SWIGSharedLibrary ========================= 

Import('default_env')

#Create environment
pyllapi_env = default_env.Clone()
pyllapi_env['BUILDERS']['PythonModule'] = SWIGSharedLibrary
pyllapi_env.ParseConfig('mysql_config --libs --cflags')
pyllapi_env.ParseConfig('python-config --cflags --libs')
	
#Read user flag for using swig or not
use_swig = int(ARGUMENTS.get("swig",0))

if use_swig==1:
	print "Building CCDB using SWIG conversion"
	
	#Setup environment
	
	#pyllapi_env.Command("echo $CCDB_CMD")
	pyllapi_lib = pyllapi_env.PythonModule('_ccdb_pyllapi', ['ccdb_pyllapi.i'], 
										SWIGFLAGS=['-c++', '-classic'], 
										LIBS=["ccdb"], 
										LIBPATH='#lib')
	pyllapi_env.InstallAs('#python/ccdb/ccdb_pyllapi/_ccdb_pyllapi.so', pyllapi_lib)
	pyllapi_env.InstallAs('#python/ccdb/ccdb_pyllapi/ccdb_pyllapi.py','ccdb_pyllapi.py')#Glob('#moo/*'))
	pyllapi_env.InstallAs('#swig/ccdb_pyllapi_wrap.cc','ccdb_pyllapi_wrap.cc')
	pyllapi_env.InstallAs('#swig/ccdb_pyllapi.py','ccdb_pyllapi.py')
else:
	print "Skipping SWIG wrapper generation. Use 'scons ... swig=1' to enable it"
	pyllapi_lib = pyllapi_env.SharedLibrary('_ccdb_pyllapi', ['ccdb_pyllapi_wrap.cc'], LIBS=["ccdb"], LIBPATH='#lib')

pyllapi_env.Append(CPPPATH = ['#include', '#src'])


#Installing 
pyllapi_env.InstallAs('#python/ccdb/ccdb_pyllapi/_ccdb_pyllapi.so', pyllapi_lib)



