ALTER TABLE variations ADD COLUMN isLocked TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE variations ADD COLUMN lockTime TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE variations ADD COLUMN lockAuthorId INT(11) NULL DEFAULT NULL;
ALTER TABLE variations ADD COLUMN goBackBehavior INT(11) NOT NULL DEFAULT 0;
ALTER TABLE variations ADD COLUMN goBackTime TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE typeTables ADD COLUMN isDeprecated TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE typeTables ADD COLUMN deprecatedById INT(11) NOT NULL DEFAULT -1;
ALTER TABLE typeTables ADD COLUMN isLocked TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE typeTables ADD COLUMN lockAuthorId INT(11) NULL DEFAULT NULL;
ALTER TABLE typeTables ADD COLUMN lockTime TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE directories ADD COLUMN isDeprecated TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE directories ADD COLUMN deprecatedById INT(11) NOT NULL DEFAULT -1;


CREATE TABLE IF NOT EXISTS `assignmentsMaterializedView` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `assignmentsId` INT NOT NULL,
    `variationsId` INT NOT NULL,
    `constantSetsId` INT NOT NULL,
    `typeTablesId` INT NOT NULL,
    `runRangesId` INT NOT NULL,
    `runMin` INT NOT NULL,
    `runMax` INT NOT NULL,
    `assignmentTime` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = MyISAM;

UPDATE schemaVersions SET schemaVersion = 5 WHERE id = 1;