name: Documentation

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - v2-main

jobs:
  deploy:
    # if: github.ref == 'refs/heads/v2-main'
    permissions:
      id-token: write
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Introspect
        run: |
          echo "--- pwd"
          pwd
          echo "--- ls ./docs/"
          ls ./docs/

      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the docsify site
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
